name: Deploy to GCE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Deploy to GCE via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCE_IP }}
          username: ${{ secrets.GCE_USER }}
          key: ${{ secrets.GCE_SSH_KEY }}
          script: |
            export PATH=$(npm bin -g):$PATH
            export PATH=$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH
            
            cd /home/${{ secrets.GCE_USER }}/motus-users-ms

            if [ ! -d ".git" ]; then
              git clone <your-repo-url> .
            else
              git pull origin main
            fi

            yarn install
            yarn build
            pm2 restart all
