name: Deploy to GCE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Deploy to GCE via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCE_IP }}
          username: ${{ secrets.GCE_USER }}
          key: ${{ secrets.GCE_SSH_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            export PATH="$HOME/.nvm/versions/node/$(node -v)/bin:$PATH"
            export PATH=$(npm bin -g):$PATH
            export PATH=$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH

            cd /home/${{ secrets.GCE_USER }}/motus-users-ms
            git pull origin main

            yarn install
            yarn build
            pm2 restart all
